// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {
    '404': { id: '404', path: '*', parentId: 'DocLayout' },
    'dumi-context-layout': { id: 'dumi-context-layout', path: '/', isLayout: true },
    DocLayout: { id: 'DocLayout', path: '/', parentId: 'dumi-context-layout', isLayout: true },
    'docs/components/themeProvider': {
      path: 'components/theme-provider',
      id: 'docs/components/themeProvider',
      parentId: 'DocLayout',
    },
    'docs/jsTools/window-scroll': {
      path: 'js-tools/window-scroll',
      id: 'docs/jsTools/window-scroll',
      parentId: 'DocLayout',
    },
    'docs/components/empty': {
      path: 'components/empty',
      id: 'docs/components/empty',
      parentId: 'DocLayout',
    },
    'docs/components/index': {
      path: 'components',
      id: 'docs/components/index',
      parentId: 'DocLayout',
    },
    'docs/test/index': { path: 'test', id: 'docs/test/index', parentId: 'DocLayout' },
    'docs/test/test': { path: 'test/test', id: 'docs/test/test', parentId: 'DocLayout' },
    'docs/index': { path: '', id: 'docs/index', parentId: 'DocLayout' },
    'demo-render': { id: 'demo-render', path: '~demos/:id', parentId: 'dumi-context-layout' },
  } as const;
  return {
    routes,
    routeComponents: {
      '404': React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__dumi__dist__client__pages__404" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/node_modules/dumi/dist/client/pages/404.js'
          ),
      ),
      'dumi-context-layout': React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/.dumi/tmp/dumi/theme/ContextWrapper'
          ),
      ),
      DocLayout: React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/node_modules/dumi/theme-default/layouts/DocLayout/index.js'
          ),
      ),
      'docs/components/themeProvider': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__themeProvider.md" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/components/themeProvider.md'
          ),
      ),
      'docs/jsTools/window-scroll': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__jsTools__window-scroll.md" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/window-scroll.md'
          ),
      ),
      'docs/components/empty': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__empty.md" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/components/empty.md'
          ),
      ),
      'docs/components/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__components__index.md" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/components/index.md'
          ),
      ),
      'docs/test/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__test__index.md" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/test/index.md'
          ),
      ),
      'docs/test/test': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__test__test.md" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/test/test.md'
          ),
      ),
      'docs/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__index.md" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/index.md'
          ),
      ),
      'demo-render': React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/node_modules/dumi/dist/client/pages/Demo/index.js'
          ),
      ),
    },
  };
}
