// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';
import { context } from './helmetContext';
import { HelmetProvider } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/node_modules/@umijs/renderer-react';

export const innerProvider = (container) => {
  return React.createElement(HelmetProvider, { context }, container);
};
