// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp';
export type { RuntimeConfig } from './core/defineApp';
export { createHistory, history } from './core/history';
export { terminal } from './core/terminal';
// test
export { TestBrowser } from './testBrowser';
// plugins
export { getSketchJSON } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/.dumi/tmp/plugin-html2sketch';
// plugins types.d.ts
// @umijs/renderer-*
export {
  createBrowserHistory,
  createHashHistory,
  createMemoryHistory,
  createSearchParams,
  generatePath,
  Helmet,
  HelmetProvider,
  Link,
  matchPath,
  matchRoutes,
  Navigate,
  NavLink,
  Outlet,
  renderClient,
  resolvePath,
  useAppData,
  useClientLoaderData,
  useLoaderData,
  useLocation,
  useMatch,
  useNavigate,
  useOutlet,
  useOutletContext,
  useParams,
  useResolvedPath,
  useRouteData,
  useRouteProps,
  useRoutes,
  useSearchParams,
  useSelectedRoutes,
  useServerLoaderData,
  withRouter,
  __getRoot,
  __useFetcher,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/node_modules/@umijs/renderer-react';
export type {
  ClientLoader,
  History,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/node_modules/@umijs/renderer-react';
// umi/client/client/plugin
export {
  ApplyPluginsType,
  PluginManager,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/node_modules/umi/client/client/plugin.js';
// react ssr
export const useServerInsertedHTML: Function = () => {};
