// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { demoIndex as dmi2 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/components/empty.md?type=demo-index';
import {
  frontmatter as fm2,
  toc as t2,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/components/empty.md?type=frontmatter';
import { demoIndex as dmi3 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/components/index.md?type=demo-index';
import {
  frontmatter as fm3,
  toc as t3,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/components/index.md?type=frontmatter';
import { demoIndex as dmi0 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/components/themeProvider.md?type=demo-index';
import {
  frontmatter as fm0,
  toc as t0,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/components/themeProvider.md?type=frontmatter';
import { demoIndex as dmi6 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/index.md?type=demo-index';
import {
  frontmatter as fm6,
  toc as t6,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/index.md?type=frontmatter';
import { demoIndex as dmi1 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/window-scroll.md?type=demo-index';
import {
  frontmatter as fm1,
  toc as t1,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/window-scroll.md?type=frontmatter';
import { demoIndex as dmi4 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/test/index.md?type=demo-index';
import {
  frontmatter as fm4,
  toc as t4,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/test/index.md?type=frontmatter';
import { demoIndex as dmi5 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/test/test.md?type=demo-index';
import {
  frontmatter as fm5,
  toc as t5,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/test/test.md?type=frontmatter';

export const filesMeta = {
  'docs/components/themeProvider': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/components/themeProvider.md?type=text'
      ),
  },
  'docs/jsTools/window-scroll': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/window-scroll.md?type=text'
      ),
  },
  'docs/components/empty': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/components/empty.md?type=text'
      ),
  },
  'docs/components/index': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/components/index.md?type=text'
      ),
  },
  'docs/test/index': {
    frontmatter: fm4,
    toc: t4,
    demoIndex: dmi4,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/test/index.md?type=text'
      ),
  },
  'docs/test/test': {
    frontmatter: fm5,
    toc: t5,
    demoIndex: dmi5,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/test/test.md?type=text'
      ),
  },
  'docs/index': {
    frontmatter: fm6,
    toc: t6,
    demoIndex: dmi6,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/index.md?type=text'
      ),
  },
};

export { tabs as tabsMeta } from './tabs';
