// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { demoIndex as dmi25 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/components/empty.md?type=demo-index';
import {
  frontmatter as fm25,
  toc as t25,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/components/empty.md?type=frontmatter';
import { demoIndex as dmi26 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/components/index.md?type=demo-index';
import {
  frontmatter as fm26,
  toc as t26,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/components/index.md?type=frontmatter';
import { demoIndex as dmi9 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/components/themeProvider.md?type=demo-index';
import {
  frontmatter as fm9,
  toc as t9,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/components/themeProvider.md?type=frontmatter';
import { demoIndex as dmi30 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/index.md?type=demo-index';
import {
  frontmatter as fm30,
  toc as t30,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/index.md?type=frontmatter';
import { demoIndex as dmi10 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/array-deepSearch.md?type=demo-index';
import {
  frontmatter as fm10,
  toc as t10,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/array-deepSearch.md?type=frontmatter';
import { demoIndex as dmi3 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/array-deepSearchAll.md?type=demo-index';
import {
  frontmatter as fm3,
  toc as t3,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/array-deepSearchAll.md?type=frontmatter';
import { demoIndex as dmi17 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/array-uniqBy.md?type=demo-index';
import {
  frontmatter as fm17,
  toc as t17,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/array-uniqBy.md?type=frontmatter';
import { demoIndex as dmi22 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/base-clone.md?type=demo-index';
import {
  frontmatter as fm22,
  toc as t22,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/base-clone.md?type=frontmatter';
import { demoIndex as dmi12 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/base-isDataType.md?type=demo-index';
import {
  frontmatter as fm12,
  toc as t12,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/base-isDataType.md?type=frontmatter';
import { demoIndex as dmi11 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/cache-localCache.md?type=demo-index';
import {
  frontmatter as fm11,
  toc as t11,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/cache-localCache.md?type=frontmatter';
import { demoIndex as dmi5 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/cache-sessionCache.md?type=demo-index';
import {
  frontmatter as fm5,
  toc as t5,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/cache-sessionCache.md?type=frontmatter';
import { demoIndex as dmi6 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/event-eventEmitter.md?type=demo-index';
import {
  frontmatter as fm6,
  toc as t6,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/event-eventEmitter.md?type=frontmatter';
import { demoIndex as dmi18 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/event-sleep.md?type=demo-index';
import {
  frontmatter as fm18,
  toc as t18,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/event-sleep.md?type=frontmatter';
import { demoIndex as dmi14 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/file-download.md?type=demo-index';
import {
  frontmatter as fm14,
  toc as t14,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/file-download.md?type=frontmatter';
import { demoIndex as dmi15 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/file-html2Pdf.md?type=demo-index';
import {
  frontmatter as fm15,
  toc as t15,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/file-html2Pdf.md?type=frontmatter';
import { demoIndex as dmi27 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/index.md?type=demo-index';
import {
  frontmatter as fm27,
  toc as t27,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/index.md?type=frontmatter';
import { demoIndex as dmi4 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/object-obj2FormData.md?type=demo-index';
import {
  frontmatter as fm4,
  toc as t4,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/object-obj2FormData.md?type=frontmatter';
import { demoIndex as dmi19 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/object-omit.md?type=demo-index';
import {
  frontmatter as fm19,
  toc as t19,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/object-omit.md?type=frontmatter';
import { demoIndex as dmi20 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/object-pick.md?type=demo-index';
import {
  frontmatter as fm20,
  toc as t20,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/object-pick.md?type=frontmatter';
import { demoIndex as dmi0 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/string-formatFileSize.md?type=demo-index';
import {
  frontmatter as fm0,
  toc as t0,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/string-formatFileSize.md?type=frontmatter';
import { demoIndex as dmi1 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/string-parseUrlParams.md?type=demo-index';
import {
  frontmatter as fm1,
  toc as t1,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/string-parseUrlParams.md?type=frontmatter';
import { demoIndex as dmi7 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/string-randomColor.md?type=demo-index';
import {
  frontmatter as fm7,
  toc as t7,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/string-randomColor.md?type=frontmatter';
import { demoIndex as dmi2 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/string-thousandFormat.md?type=demo-index';
import {
  frontmatter as fm2,
  toc as t2,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/string-thousandFormat.md?type=frontmatter';
import { demoIndex as dmi23 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/string-tm.md?type=demo-index';
import {
  frontmatter as fm23,
  toc as t23,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/string-tm.md?type=frontmatter';
import { demoIndex as dmi21 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/string-uuid.md?type=demo-index';
import {
  frontmatter as fm21,
  toc as t21,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/string-uuid.md?type=frontmatter';
import { demoIndex as dmi24 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/validates.md?type=demo-index';
import {
  frontmatter as fm24,
  toc as t24,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/validates.md?type=frontmatter';
import { demoIndex as dmi13 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/window-copyText.md?type=demo-index';
import {
  frontmatter as fm13,
  toc as t13,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/window-copyText.md?type=frontmatter';
import { demoIndex as dmi8 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/window-fullScreen.md?type=demo-index';
import {
  frontmatter as fm8,
  toc as t8,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/window-fullScreen.md?type=frontmatter';
import { demoIndex as dmi16 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/window-scroll.md?type=demo-index';
import {
  frontmatter as fm16,
  toc as t16,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/window-scroll.md?type=frontmatter';
import { demoIndex as dmi28 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/test/index.md?type=demo-index';
import {
  frontmatter as fm28,
  toc as t28,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/test/index.md?type=frontmatter';
import { demoIndex as dmi29 } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/test/test.md?type=demo-index';
import {
  frontmatter as fm29,
  toc as t29,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/test/test.md?type=frontmatter';

export const filesMeta = {
  'docs/jsTools/string-formatFileSize': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/string-formatFileSize.md?type=text'
      ),
  },
  'docs/jsTools/string-parseUrlParams': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/string-parseUrlParams.md?type=text'
      ),
  },
  'docs/jsTools/string-thousandFormat': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/string-thousandFormat.md?type=text'
      ),
  },
  'docs/jsTools/array-deepSearchAll': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/array-deepSearchAll.md?type=text'
      ),
  },
  'docs/jsTools/object-obj2FormData': {
    frontmatter: fm4,
    toc: t4,
    demoIndex: dmi4,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/object-obj2FormData.md?type=text'
      ),
  },
  'docs/jsTools/cache-sessionCache': {
    frontmatter: fm5,
    toc: t5,
    demoIndex: dmi5,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/cache-sessionCache.md?type=text'
      ),
  },
  'docs/jsTools/event-eventEmitter': {
    frontmatter: fm6,
    toc: t6,
    demoIndex: dmi6,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/event-eventEmitter.md?type=text'
      ),
  },
  'docs/jsTools/string-randomColor': {
    frontmatter: fm7,
    toc: t7,
    demoIndex: dmi7,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/string-randomColor.md?type=text'
      ),
  },
  'docs/jsTools/window-fullScreen': {
    frontmatter: fm8,
    toc: t8,
    demoIndex: dmi8,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/window-fullScreen.md?type=text'
      ),
  },
  'docs/components/themeProvider': {
    frontmatter: fm9,
    toc: t9,
    demoIndex: dmi9,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/components/themeProvider.md?type=text'
      ),
  },
  'docs/jsTools/array-deepSearch': {
    frontmatter: fm10,
    toc: t10,
    demoIndex: dmi10,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/array-deepSearch.md?type=text'
      ),
  },
  'docs/jsTools/cache-localCache': {
    frontmatter: fm11,
    toc: t11,
    demoIndex: dmi11,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/cache-localCache.md?type=text'
      ),
  },
  'docs/jsTools/base-isDataType': {
    frontmatter: fm12,
    toc: t12,
    demoIndex: dmi12,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/base-isDataType.md?type=text'
      ),
  },
  'docs/jsTools/window-copyText': {
    frontmatter: fm13,
    toc: t13,
    demoIndex: dmi13,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/window-copyText.md?type=text'
      ),
  },
  'docs/jsTools/file-download': {
    frontmatter: fm14,
    toc: t14,
    demoIndex: dmi14,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/file-download.md?type=text'
      ),
  },
  'docs/jsTools/file-html2Pdf': {
    frontmatter: fm15,
    toc: t15,
    demoIndex: dmi15,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/file-html2Pdf.md?type=text'
      ),
  },
  'docs/jsTools/window-scroll': {
    frontmatter: fm16,
    toc: t16,
    demoIndex: dmi16,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/window-scroll.md?type=text'
      ),
  },
  'docs/jsTools/array-uniqBy': {
    frontmatter: fm17,
    toc: t17,
    demoIndex: dmi17,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/array-uniqBy.md?type=text'
      ),
  },
  'docs/jsTools/event-sleep': {
    frontmatter: fm18,
    toc: t18,
    demoIndex: dmi18,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/event-sleep.md?type=text'
      ),
  },
  'docs/jsTools/object-omit': {
    frontmatter: fm19,
    toc: t19,
    demoIndex: dmi19,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/object-omit.md?type=text'
      ),
  },
  'docs/jsTools/object-pick': {
    frontmatter: fm20,
    toc: t20,
    demoIndex: dmi20,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/object-pick.md?type=text'
      ),
  },
  'docs/jsTools/string-uuid': {
    frontmatter: fm21,
    toc: t21,
    demoIndex: dmi21,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/string-uuid.md?type=text'
      ),
  },
  'docs/jsTools/base-clone': {
    frontmatter: fm22,
    toc: t22,
    demoIndex: dmi22,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/base-clone.md?type=text'
      ),
  },
  'docs/jsTools/string-tm': {
    frontmatter: fm23,
    toc: t23,
    demoIndex: dmi23,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/string-tm.md?type=text'
      ),
  },
  'docs/jsTools/validates': {
    frontmatter: fm24,
    toc: t24,
    demoIndex: dmi24,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/validates.md?type=text'
      ),
  },
  'docs/components/empty': {
    frontmatter: fm25,
    toc: t25,
    demoIndex: dmi25,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/components/empty.md?type=text'
      ),
  },
  'docs/components/index': {
    frontmatter: fm26,
    toc: t26,
    demoIndex: dmi26,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/components/index.md?type=text'
      ),
  },
  'docs/jsTools/index': {
    frontmatter: fm27,
    toc: t27,
    demoIndex: dmi27,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/jsTools/index.md?type=text'
      ),
  },
  'docs/test/index': {
    frontmatter: fm28,
    toc: t28,
    demoIndex: dmi28,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/test/index.md?type=text'
      ),
  },
  'docs/test/test': {
    frontmatter: fm29,
    toc: t29,
    demoIndex: dmi29,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/test/test.md?type=text'
      ),
  },
  'docs/index': {
    frontmatter: fm30,
    toc: t30,
    demoIndex: dmi30,
    textGetter: () =>
      import(
        /* webpackChunkName: "meta__docs" */ '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/docs/index.md?type=text'
      ),
  },
};

export { tabs as tabsMeta } from './tabs';
