// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { history, useOutlet } from 'dumi';
import React, { useEffect, useRef, useState } from 'react';
import { locales } from '../locales/config';
import { components } from '../meta/atoms';
import {
  SiteContext,
  type ISiteContext,
} from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/node_modules/dumi/dist/client/theme-api/context.js';
import { warning } from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/node_modules/rc-util';

const entryExports = {};

// Static content
const pkg = { name: 'cwj-components-docs', version: '1.0.0' };
const historyType = 'browser';
const hostname = undefined;
const themeConfig = {
  footer:
    'Copyright © 2024 | Powered by <a href="https://d.umijs.org" target="_blank" rel="noreferrer">dumi</a>',
  prefersColor: { default: 'light', switch: true },
  nprogress: true,
  lastUpdated: true,
};
const _2_level_nav_available = false;

export default function DumiContextWrapper() {
  const outlet = useOutlet();
  const [loading, setLoading] = useState(false);
  const prev = useRef(history.location.pathname);

  useEffect(() => {
    return history.listen((next) => {
      if (next.location.pathname !== prev.current) {
        prev.current = next.location.pathname;

        // scroll to top when route changed
        document.documentElement.scrollTo(0, 0);
      }
    });
  }, []);

  const context: ISiteContext = React.useMemo(() => {
    const ctx = {
      pkg,
      historyType,
      entryExports,
      demos: null,
      components,
      locales,
      loading,
      setLoading,
      hostname,
      themeConfig,
      _2_level_nav_available,
    };

    // Proxy do not warning since `Object.keys` will get nothing to loop
    Object.defineProperty(ctx, 'demos', {
      get: () => {
        warning(false, '`demos` return empty in latest version, please use `useDemo` instead.');
        return {};
      },
    });

    return ctx;
  }, [
    pkg,
    historyType,
    entryExports,
    components,
    locales,
    loading,
    setLoading,
    hostname,
    themeConfig,
    _2_level_nav_available,
  ]);

  return <SiteContext.Provider value={context}>{outlet}</SiteContext.Provider>;
}
