// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { useSiteData } from 'dumi';
import { useLayoutEffect, type FC } from 'react';
import './nprogress.css';
import UserLoading from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/node_modules/dumi/dist/client/pages/Loading';
import nprogress from '/Users/caowenjing/Documents/React练习/组件库/cwj-components-docs/node_modules/nprogress';

const DumiLoading: FC = () => {
  const { setLoading } = useSiteData();

  useLayoutEffect(() => {
    setLoading(true);
    nprogress.start();

    return () => {
      setLoading(false);
      nprogress.done();
    };
  }, []);

  return <UserLoading />;
};

export default DumiLoading;
